/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.wnuke.botmanager

fun main(args: Array<String>) {
    var botBuildPath = ""
    if (args.isNotEmpty()) {
        botBuildPath = args[0]
    }
    val dockerAPI = DockerAPI()
    dockerAPI.buildBotImage(botBuildPath)
    dockerAPI.printContainers()
}

